#!/bin/zsh
clear

# 2015-2017 - Licensed under GPL, any version
# Please see the LICENCE.txt file

# This is the location of your log-file.
MYLOG=~/.config/mylog/mylog

# Here you set the colors you want in the output of view and search
# 
# Black       0;30     Dark Gray     1;30
# Blue        0;34     Light Blue    1;34
# Green       0;32     Light Green   1;32
# Cyan        0;36     Light Cyan    1;36
# Red         0;31     Light Red     1;31
# Purple      0;35     Light Purple  1;35
# Brown       0;33     Yellow        1;33
# Light Gray  0;37     White         1;37
ONE="\033[1;32m"
TWO="\033[1;33m"
W="\033[1;37m"
END="\033[0m"
#
#

# You don't have to edit anything beyond this line.
#
VERSION="0.8.2"
DATE=$( date "+%F %T" )

if [[ ! -f ${MYLOG} ]]; then
	echo "Do you want to set up MyLog? (Y/n)\c"
	read setup

	if [[ ${setup} == "" || ${setup} == "Y" || ${setup} == "y" ]]; then
		echo "Creating the MyLog dir and file"
		mkdir -p ${MYLOG:h}
		touch ${MYLOG}

		echo "Creating symlinks for myview and mysearch where you places mylog"
		ln -s ${0} ${0:h}/myview
		ln -s ${0} ${0:h}/mysearch

		echo "${0:t} v${VERSION} successfully installed"
		echo "${DATE} * INSTALLED * ${0:t} v${VERSION} successfully installed" > ${MYLOG}
	else
		echo "Aborting the installation of ${0:t} v${VERSION}"
		exit
	fi
	exit
fi

if [[ ${1} == "-h" ]]; then
	echo "${W}${0:t} v${VERSION}\n"
	echo "\033[1;32mThis is a small logging script for one line notes that you'd like to keep for\nfuture reference. It's nothing fancy, but it does the job for me.$END"
	echo ""
	echo "${W}Usage:${E}"
	echo "\t\033[1;32m${0:t} <Enter>"
	echo "\t${0:t} -v (or myview) - View the changelog"
	echo "\t${0:t} -s (or mysearch) - Search, case insensitive"
  echo "\t${0:t} -tags - This will show a list of tags you've used, sorted\n\t      alphabetically. If you have YAD installed, it will display a window${END}"
	echo "\n\033[1;33mScripted by Stig-Ørjan Smelror <smelror@gmail.com>$END\n"
	exit
fi
if [[ ${1} == "-v" || ${0:t} == "myview" ]]; then
	cat ${MYLOG} | awk -F'*' '{print "\033[1;37m"$1"-\033[0m""\033[1;32m"$2"-""\033[0m", "\033[1;33m"$3"\033[0m"}'
	exit
fi
if [[ ${1} == "-s" || ${0:t} == "mysearch" ]]; then
	if [[ ${0:t} == "mysearch" ]]; then
		S=${1}
	else
		S=${2}
	fi
	cat ${MYLOG} | grep -iw ${S} | awk -F'*' '{print "\033[1;37m"$1"-\033[0m""\033[1;32m"$2"-""\033[0m", "\033[1;33m"$3"\033[0m"}'
	exit
fi
if [[ ${1} == "-tags" ]]; then
	if [[ $(cat ${MYLOG} | awk '{print $4}' | sort -u | uniq -u) != "" ]]; then
        TAGS=$(cat ${MYLOG} | awk '{print $4}' | sort -u | uniq -u)
				echo ${TAGS} | while read MyTags
					do
						NUMTAGS=$(cat ${MYLOG} | grep -w " ${MyTags:u} " | wc -l)
						echo "${MyTags}\t(${NUMTAGS})" >> /tmp/MyTags
				done
				if [[ ! -f $(which yad) ]]; then
					cat /tmp/MyTags
				else
					fc=$(cat /tmp/MyTags | yad --list --center --title="MyLog Tags" --column="List" --separator="" --width=400 --height=600 --button="gtk-close:10")
        fi
				rm -f /tmp/MyTags
				exit
    else
        echo "You have nothing in your log at the moment."
        exit
    fi
fi 

echo "${W}Your log entry:${END}"
read LOG
echo "${W}How do you want to tag this entry?${END}"
read TAG

echo ${DATE} "* ${TAG:u} * ${LOG}" >> ${MYLOG}

clear
echo "\n${ONE}* Entry added to your changelog *${END}"
echo "\033[1;35m* ${0:t} -h to show help *${END}\n"
exit 0
