#!/bin/zsh
clear

# 2015 - Licensed under GPL, any version

# How to install
#
# 1. Download script and place it in your path. I use ~/bin/
# 2. Create a directory called ~/.mylog (mkdir ~/.mylog)
# 3. Create a file called changelog (touch ~.mylog/mylog)
# 4. Create symlinks for the other functions
# 4.1. ln -s ~/bin/mylog ~/bin/myview
# 4.2. ln -s ~/bin/mylog ~/bin/mysearch
# 5. Protect your log
# 5.1. chmod 740 ~/.mylog

# Changelog
# 0.1 - Initial version
# 0.2 - Bugfixes
# 0.3 - Added colored output
#     - Change name from changelog to mylog
#     - Added a howto to install and setup
# 0.4 - Added a TAG to make searching for similar entries easier
# 0.5 - Interactive instead of inline logging.
#     - Added -h option to show help text
# 0.55 - Added more colored
#      - Cleaned up a little bit
# 0.6 - Added a complete setup system
#     - Removed some clutter
#

# This is the location of your log-file.
CHANGELOG=~/.mylog/mylog

# Here you set the colors you want in the output of view and search
# 
# Black       0;30     Dark Gray     1;30
# Blue        0;34     Light Blue    1;34
# Green       0;32     Light Green   1;32
# Cyan        0;36     Light Cyan    1;36
# Red         0;31     Light Red     1;31
# Purple      0;35     Light Purple  1;35
# Brown       0;33     Yellow        1;33
# Light Gray  0;37     White         1;37
ONE="\033[1;32m"
TWO="\033[1;33m"
END="\033[0m"
#
#

# You don't have to edit anything beyond this line.
#
VERSION="0.6"
DATE=$( date "+%F %T" )

if [[ ${1} == "-h" ]]; then
	echo "\033[1;34mThis is a small logging script for one line notes that you'd like to keep for future reference."
	echo "It's nothing fancy, but it does the job for me.$END"
	echo "$0:t v$VERSION"
	echo "Usage:"
	echo "\t\033[0;34m$0:t <Enter>"
	echo "\t$0:t -v (or myview) - View the changelog"
	echo "\t$0:t -s (or mysearch) - Search, case insensitive$END"
	echo "\n\033[1;33mScripted by Stig-Ørjan Smelror <smelror@gmail.com>$END"
	exit
fi
if [[ ${1} == "-v" || ${0:t} == "myview" ]]; then
	cat ${CHANGELOG} | awk -F'*' '{print "\033[1;37m"$1"-\033[0m""\033[1;32m"$2"-""\033[0m", "\033[1;33m"$3"\033[0m"}'
	exit
fi
if [[ ${1} == "-s" || ${0:t} == "mysearch" ]]; then
	if [[ ${0:t} == "mysearch" ]]; then
		S=${1}
	else
		S=${2}
	fi
	grep -i ${S} ${CHANGELOG} | awk -F'*' '{print "\033[0;31m"${1}"-\033[0m""\033[1;32m"${2}"-""\033[0m", "\033[1;33m"${3}"\033[0m"}'
	exit
fi

echo "Your log entry:"
read LOG
echo "How do you want to tag this entry?"
read TAG
#TAG=`echo ${TAG} | tr '[:lower:]' '[:upper:]'`

echo ${DATE} "* ${TAG:u} * ${LOG}" >> ${CHANGELOG}

clear
echo "\n${ONE}* Entry added to your changelog *${END}"
echo "\033[1;35m* ${0:t} -h to show help *${END}\n"
exit 0
